### ISSUE TITLE
Disable Phased seek bar

### ISSUE THREAD

**Issue by AbhiShah29** [ademar111190/android-phased-seek-bar#2]
Hi,
How to enable/disable phased seek bar?

I tried with
        psb.setClickable(false);
        psb.setEnabled(false);
        psb.setFocusable(false);
but nothing worked for me.

I want to disable psb at the time of activity create and enable it on button click.
Will you please help me in achieving this?

Thanks in advance.

**Comment by ademar111190** [comment]
Good question @AbhiShah29, currently there is no support, but it is simple to add it, unfortunately I have no time for the next two weeks, so if you want you can make a pull request, otherwise I'll add this feature only in the next month.

**Comment by AbhiShah29** [comment]
@ademar111190  can you give me some idea how to enable disable it?
Will generate pull request once achieve it.

**Comment by ademar111190** [comment]
Sure @AbhiShah29 , the `PhasedSeekBar` class manipulate the touch event on `onTouchEvent` method, so what we need is verify if the view is on a valid state, e.g. "not disabled", and execute the logic only in this case

**Comment by AbhiShah29** [comment]
Done..
Generating pull request.
Thanks.

**Comment by ademar111190** [comment]
Thank you @AbhiShah29 , I accepted your pull request.
